name: CI
on:
  push:
  pull_request:
jobs:
  xenial:
    container: 
      image: vapor/swift:5.2-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test --enable-test-discovery --enable-code-coverage --sanitize=thread
  bionic:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Bionic Tests
      run: swift test --enable-test-discovery --enable-code-coverage --sanitize=thread
    - name: Setup container for codecov upload
      run: apt-get update && apt-get install curl
    - name: Process coverage file
      run: llvm-cov show .build/x86_64-unknown-linux-gnu/debug/VaporCSRFPackageTests.xctest -instr-profile=.build/debug/codecov/default.profdata > coverage.txt
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_UPLOAD_KEY }}
        file: coverage.txt
